---
title: "SES and Weight Loss Behavior"
description: |
  How is socioeconomic status (SES) associated with engagement in various weight loss behaviors?
author: [Songyi Ahn]
date: 2025-03-08
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, eval=TRUE, warning=FALSE, message=FALSE)
```

```{r}
library(rio)
library(here)
library(tidyverse)
library(ggridges)
```

```{r}
weight3 <- import(here("data", "sesdata.rds"))
```

# First Draft
```{r}
weight3 %>%
  ggplot(aes(x = SES, y = weight_loss_behavior_type, group = weight_loss_behavior_type)) +
  geom_density_ridges()
```

# Second Draft
```{r}
weight3 %>%
  ggplot(aes(x = SES, y = weight_loss_behavior_type, fill = weight_loss_behavior_type)) +
  geom_density_ridges(alpha = 0.8) +  
  scale_fill_viridis_d() +
  theme_minimal() +
  stat_summary(
    aes(label = weight_loss_behavior_type),  
    fun = median, 
    geom = "text",
    color = "white",  
    size = 2,  
    hjust = 0.8,  
    vjust = -3
  ) +
  theme(axis.text.y = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank()) +
  scale_x_continuous(breaks = c(1, 4),
                     labels = c("Low", "High")) +
  labs(x = "SES", y = "Weight Loss Behavior Type", fill = "Weight Loss Method",
       title = "Variation in Weight Loss Methods Across SES Groups")
```