---
title: "SES and Weight Perception"
description: |
  How is socioeconomic status (SES) associated with an individual's perceptions of their own weight?
author: [Songyi Ahn]
date: 2025-03-07
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, eval=TRUE, warning=FALSE, message=FALSE)
```

```{r}
library(rio)
library(here)
library(tidyverse)
```

```{r}
weight1 <- import(here("data", "sesdata.rds"))
```

# First Draft
```{r}
weight1 %>%
ggplot(aes(x = SES, y = BMI, color = weight_perception)) +
  geom_jitter(width = 0.2, alpha = 0.7) +
  theme_minimal()
```

# Second Draft
```{r}
weight1 %>%
ggplot(aes(x = SES, y = BMI)) +
  geom_point(aes(color = weight_perception)) +  
  geom_smooth(data = weight1 %>% filter(weight_perception %in% c("overweight", "right weight")),
              aes(color = weight_perception),
              method = "lm", se = FALSE) +
  ylim(NA, 50) +
  scale_color_viridis_d() +
  theme_minimal() +
  scale_x_continuous(breaks = c(1, 4),
                     labels = c("Low", "High")) +
  labs(x = "SES", y = "BMI", color = "Weight Perception",
       title = "Differences in Weight Perception by SES at the Same BMI")
```

### Final Plot
```{r}

```


